### Getting to Know Quarto

<!--- using quarto to produce different formats from the same file --->

+---------------+----------------+-----------------------------------------+
| Time          | Module         | **Section & Activities**                |
+===============+================+=========================================+
| 09:00-09:15   | Hello Quarto!  | Welcome                                 |
+---------------+----------------+-----------------------------------------+
| 09:15-09:35   |                | What is Quarto?                         |
|               |                |                                         |
|               |                | -   My Turn: A Tour of Rstudio          |
+---------------+----------------+-----------------------------------------+
| 09:35-09:50   |                | Your Turn: `my_first_doc.qmd`           |
|               |                |                                         |
|               |                | -   Source/Visual mode + basic Markdown |
+---------------+----------------+-----------------------------------------+
| 09:50-10:00   |                | Your Turn: Rendering in Rstudio         |
|               |                |                                         |
|               |                | -   alternative methods, under the hood |
+---------------+----------------+-----------------------------------------+
| 10:00-10:10   | PAUSE          |                                         |
+---------------+----------------+-----------------------------------------+
| 10:10-10:25   | Quarto Formats | Anatomy of a Document                   |
|               |                |                                         |
|               |                | Quarto Formats                          |
|               |                |                                         |
|               |                | -   Our Turn: Rendering Other Formats   |
+---------------+----------------+-----------------------------------------+
| 10:25-10:40   |                | YAML                                    |
|               |                |                                         |
|               |                | -   Your Turn: Quarto YAML Intelligence |
+---------------+----------------+-----------------------------------------+
| 10:40-10:50   | PAUSE          |                                         |
+---------------+----------------+-----------------------------------------+
| 10:50-11:20   | Articles       |                                         |
+---------------+----------------+-----------------------------------------+
| 10:20-11:30   | WRAP-UP        |                                         |
+---------------+----------------+-----------------------------------------+

Notes:

- Ran overtime to 12PM
- Lots of troubleshooting with PDF rendering:
    - introduce `latex` format earlier
    - put render `.qmd` to `.pdf` in prework!

Next time:

- Rtools needed to install tinytex on Windows computers
- include aside on MathJax in Articles / LaTex
- FOCUS on PDF/Tex output first!
    - introduce multi-format rendering earlier!
- My Turn: A Tour should be more impressive!
    - go straight for elsivier template!
    - show off some websites
- Sign up questions:
    - markdown?
    - git/GitHub?
- Swap Articles and Doc Formats order
    - show valid YAML = render dropdowns in RStudio
